AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AMI:
    Description: WebServer EC2 instance type
    Type: String
    Default: ami-04932daa2567651e7
  DBPswd:
    Description: WebServer EC2 instance type
    Type: String
    Default: qwerty123
Resources:
  WebAutoscalling:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: 1
      MinSize: 1
      LaunchConfigurationName: !Ref LaunchConfig
      VPCZoneIdentifier:
        - !Ref PublicSubnet
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: t2.micro
      KeyName: frank
      IamInstanceProfile: !Ref RoleToInstance
      ImageId: !Ref AMI
      SecurityGroups:
        - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub
          "#!/bin/bash \n
          sudo apt update -y \n
          sudo sudo apt install apt-transport-https ca-certificates curl software-properties-common -y \n
          echo '2' \n
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \n
          echo '3' \n
          sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable\" \n
          echo '4' \n
          sudo apt update -y \n
          echo '5' \n
          sudo apt install docker-ce -y \n
          echo '6' \n
          sudo docker run -d  --name srv --restart always -p 8080:8080 -i karpovichart/web_srv python3 /srv/srv.py -p ${DBPswd} -u postgres -ho ${PostgresInstance.Endpoint.Address}  -d test"
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: testbbucket31
  PostgresInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 11.5
      AllocatedStorage: 20
      DBInstanceClass: 'db.t2.micro'
      DBName: "test"
      DBSubnetGroupName: !Ref DBSubnetGroups
      MasterUsername: "postgres"
      MasterUserPassword: !Ref DBPswd
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server
      GroupName: web
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Database SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - FromPort: 5432
          IpProtocol: tcp
          ToPort: 5432
          CidrIp: 0.0.0.0/0
  VPC:
    Type: AWS::EC2::VPC
    Properties:

      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: Yes
      AvailabilityZone:  "eu-central-1b"
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: PublicRoute
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "eu-central-1c"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Private
  DBSubnetGroups:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "subnet group"
      SubnetIds:
        - !Ref PrivateSubnet
        - !Ref PublicSubnet
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable
  Ec2Role1:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: s3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: "Allow"
              Action: "s3:*"
              Resource: "*"
#      RoleName: EC2ROLE
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  RoleToInstance:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref "Ec2Role1"
Outputs:
  SampleStringOutput:
    Value: 'complite!'
    Description: "Sample random string generated by lambda function using Node.js"
